defmodule GuildfordVueWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :guildford_vue

  # Session cookie hardening (Sprint 11.5 Slice 2):
  #
  #   * `http_only: true` — defence-in-depth against XSS reading
  #     the session cookie. CSP already blocks inline + 3rd-party
  #     scripts (`lib/guildford_vue_web/plugs/secure_headers.ex`)
  #     so this is belt-and-braces.
  #   * `secure: Mix.env() == :prod` — only transmit over HTTPS
  #     in production. Dev/test use plain HTTP loopback so we
  #     can't unconditionally set this.
  #   * `encryption_salt` — encrypts session content at rest in
  #     the cookie. Previously only signed (tamper-evident but
  #     readable to anyone who could sniff the cookie).
  #   * `same_site: "Lax"` — kept; defence against CSRF on
  #     top-level navigation.
  @session_options [
    store: :cookie,
    key: "_guildford_vue_key",
    signing_salt: "5lcIdwAB",
    encryption_salt: "5lcEncrYpt",
    same_site: "Lax",
    http_only: true,
    secure: Mix.env() == :prod
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options, peer_data: true, x_headers: true]],
    longpoll: [connect_info: [session: @session_options, peer_data: true, x_headers: true]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :guildford_vue,
    gzip: not code_reloading?,
    only: GuildfordVueWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :guildford_vue
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug GuildfordVueWeb.Router
end
