import Config

# Configure your database
config :guildford_vue, GuildfordVue.Repo,
  username: "postgres",
  # secrets:allow local docker-compose dev DB (not real PII; prod reads DATABASE_URL via runtime.exs)
  password: "postgres",
  hostname: "localhost",
  # host port 5434 forwards to the docker-compose postgres+postgis container
  # (host ports 5432/5433 are held by the sftgen project on this machine)
  port: 5434,
  database: "guildford_vue_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  types: GuildfordVue.PostgresTypes,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :guildford_vue, GuildfordVueWeb.Endpoint,
  # Bind to all interfaces so the dev server is reachable from other
  # devices on the LAN (phones, tablets, other laptops). Loopback-only
  # binding (`{127, 0, 0, 1}`) restricts to this machine.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "3Q848vHVxGa1M4gjhzZzDafcBKrBomy12HXHd2haQM2CyGvTXgl7j+Oj+VQGQFeu",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:guildford_vue, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:guildford_vue, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :guildford_vue, GuildfordVueWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/guildford_vue_web/router\.ex$"E,
      ~r"lib/guildford_vue_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :guildford_vue, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Sprint 9 Slice 3 — dev uses the real ChromicPDF adapter so the
# /candidate/bookings/.../receipt.pdf URL actually serves a PDF.
# Tests stay on the Stub (config/config.exs default).
#
# Auto-fall-back: if no Chromium/Chrome binary is on PATH, drop to
# the Stub adapter so the server still boots. The Stub returns
# HTML; ReceiptController sniffs the %PDF magic bytes and serves
# text/html vs application/pdf accordingly, so the receipt URL
# still works — it just renders the receipt as HTML in the browser.
if Enum.any?(
     ~w(chromium-browser chromium google-chrome chrome),
     &System.find_executable/1
   ) do
  config :guildford_vue, :start_chromic_pdf, true
  config :guildford_vue, :pdf_generator, GuildfordVue.PDFGenerator.Chromic
else
  config :guildford_vue, :start_chromic_pdf, false
  config :guildford_vue, :pdf_generator, GuildfordVue.PDFGenerator.Stub
end
